# Generated by Django 4.1 on 2022-08-13 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30)),
                ('entrada', models.CharField(max_length=8)),
                ('saida', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='UserPerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edv', models.CharField(max_length=15)),
                ('nome', models.CharField(max_length=150)),
                ('senha', models.CharField(max_length=200)),
                ('dia_curso', models.CharField(choices=[('SEG', 'Segunda'), ('TER', 'Terca'), ('QUA', 'Quarta'), ('QUI', 'Quinta'), ('SEX', 'Sexta')], default=None, max_length=3)),
                ('perm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.userperm')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.turno')),
            ],
        ),
    ]
