# Generated by Django 4.1 on 2022-08-14 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Justificativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocorrencia', models.CharField(choices=[('Atraso na Entrada', 'Atraso Na Entrada'), ('Saída antecipada', 'Saida Antecipada'), ('Falta', 'Falta'), ('Afastamento', 'Afastamento'), ('Intervalo Irregular', 'Intervalo Irregular'), ('Crachá provisório', 'Cracha Provisorio')], default=None, max_length=30)),
                ('data_1', models.CharField(max_length=10)),
                ('data_2', models.CharField(max_length=10)),
                ('marcacao_1', models.TimeField()),
                ('marcacao_2', models.TimeField()),
                ('motivo', models.TextField(max_length=2000)),
                ('justificado', models.CharField(choices=[('S', 'Sim'), ('N', 'Nao')], default='N', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='perm',
            field=models.CharField(choices=[('Admin', 'Administrador'), ('Super usuário', 'Super Usuario'), ('Usuário', 'Usuario')], default='Usuário', max_length=30),
        ),
        migrations.DeleteModel(
            name='UserPerm',
        ),
        migrations.AddField(
            model_name='justificativa',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.colaborador'),
        ),
    ]
