# Generated by Django 4.0.6 on 2022-08-26 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_data_1_justificativa_data_fim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='turno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.turno'),
        ),
    ]
