# Generated by Django 4.0.6 on 2022-08-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_colaborador_turno"),
    ]

    operations = [
        migrations.AddField(
            model_name="colaborador",
            name="email",
            field=models.EmailField(default="email", max_length=254),
            preserve_default=False,
        ),
    ]
