# Generated by Django 4.0.6 on 2022-08-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_colaborador_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justificativa',
            name='data_fim',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='justificativa',
            name='data_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='justificativa',
            name='motivo',
            field=models.TextField(max_length=400),
        ),
    ]
