# Generated by Django 4.1.2 on 2022-11-10 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0002_alter_sneaker_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneaker',
            name='condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sneakers.condition'),
        ),
    ]
