# Generated by Django 4.1 on 2022-09-21 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=3)),
                ('card_type', models.CharField(choices=[('G', 'Gold'), ('E', 'Exclusive'), ('P', 'Platinum')], default='G', max_length=10)),
                ('expiration_date', models.DateField()),
                ('invoice_expiration_day', models.PositiveSmallIntegerField()),
                ('card_flag', models.CharField(max_length=30)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=80)),
                ('cpf', models.CharField(max_length=11)),
                ('sexo', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birth_date', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('created_at', models.DateField(auto_now=True)),
                ('good_client', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('passworld', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_transfer', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_of_transfer', models.DateField(auto_now=True)),
                ('user_receive', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_receive', to='accounts.client')),
                ('user_transfer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_transfer', to='accounts.client')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('invoice_expiration_date', models.DateField()),
                ('invoice_payed_date', models.DateField()),
                ('is_expired', models.BooleanField(default=False)),
                ('invoice_card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.card')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
        migrations.AddField(
            model_name='card',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.client'),
        ),
        migrations.CreateModel(
            name='AdvancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('advance_payment_day', models.DateField()),
                ('advance_expire_day', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.client')),
            ],
        ),
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('advance_fees', models.DecimalField(decimal_places=2, max_digits=5)),
                ('advance_installments', models.PositiveSmallIntegerField()),
                ('advance_status', models.CharField(choices=[('A', 'Approved'), ('R', 'Recused'), ('W', 'Waiting')], default='W', max_length=12)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.client')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=5)),
                ('account', models.CharField(max_length=8)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
            ],
        ),
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoices', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.invoice')),
                ('transfers', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.transfers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.user')),
            ],
        ),
    ]
