# Generated by Django 4.1 on 2022-09-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_passworld_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
