# Generated by Django 4.1.2 on 2022-12-02 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_client_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfers',
            name='user_receive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_receive', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='user_transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_transfer', to='accounts.account'),
        ),
    ]
