# Generated by Django 4.1.2 on 2022-11-21 11:05

from django.db import migrations
import pictures.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image',
            field=pictures.models.PictureField(aspect_ratios=[None], breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, default=1, file_types=['WEBP'], grid_columns=12, pixel_densities=[1, 2], upload_to='user_images'),
            preserve_default=False,
        ),
    ]
