# Generated by Django 4.1 on 2022-08-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sneakers',
            old_name='marca',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='sneakers',
            old_name='estado',
            new_name='condition',
        ),
        migrations.RenameField(
            model_name='sneakers',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sneakers',
            old_name='ano_lancamento',
            new_name='releaser_year',
        ),
    ]
