# Generated by Django 4.1 on 2022-08-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_rename_marca_sneakers_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneakers',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
